#!/usr/bin/env bash

set -exo pipefail

CACHE_HIT="${1:-false}"

# github runner knocks out with -jN>=4
export MAKEFLAGS="-j"

cd "${CHIPYARD_DIR}"

if [[ -z "${CONDA_ENV_DIR:-}" ]]; then
    echo "error: CONDA_ENV_DIR must be set" >&2
    exit 1
fi

mkdir -p "$(dirname "${CONDA_ENV_DIR}")"

cat > "${CHIPYARD_DIR}/env.sh" <<EOF
# line auto-generated by .github/scripts/setup-chipyard.sh
if ! type conda >& /dev/null; then
    echo "::ERROR:: you must have conda in your environment first"
    return 1
fi

source \$(conda info --base)/etc/profile.d/conda.sh
conda activate "${CONDA_ENV_DIR}"
source "${CHIPYARD_DIR}/scripts/fix-open-files.sh"
EOF

if [[ "${CACHE_HIT}" == "true" ]]; then
    echo "[CI] Cache hit! Skipping conda and toolchain steps"
    export RISCV="${CONDA_ENV_DIR}/riscv-tools"
    [ -d "${RISCV}" ] || ( echo "error: ${RISCV} does not exist!" && exit 1 )
    source $(conda info --base)/etc/profile.d/conda.sh
    conda activate "${CONDA_ENV_DIR}"
    ./build-setup.sh --conda-env-name "${CONDA_ENV_DIR}" riscv-tools \
        --skip-conda --skip-toolchain --skip-ctags --skip-precompile --skip-firesim --skip-marshal --skip-circt
else
    ./build-setup.sh --conda-env-name "${CONDA_ENV_DIR}" riscv-tools \
        --skip-ctags --skip-precompile --skip-firesim --skip-marshal
fi
